program Project1;

{$R *.dres}

uses
  System.StartUpCopy,
  FMX.Forms,
  uMainForm in 'uMainForm.pas' {MainForm},
  uFrameMap in 'uFrameMap.pas' {FrameMap: TFrame},
  uGlobal in 'uGlobal.pas',
  uFramePercs in 'uFramePercs.pas' {FramePercs: TFrame},
  uFrameDetector in 'uFrameDetector.pas' {FrameDetector: TFrame},
  uScanerWiFi in 'uScanerWiFi.pas',
  uFrameQRScaner in 'uFrameQRScaner.pas' {FrameQRScanner: TFrame},
  ZXing.BarcodeFormat in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.BarcodeFormat.pas',
  ZXing.BaseLuminanceSource in '..\ZXing.Delphi-3.10.0\Lib\Classes\Filtering\ZXing.BaseLuminanceSource.pas',
  ZXing.Binarizer in '..\ZXing.Delphi-3.10.0\Lib\Classes\Filtering\ZXing.Binarizer.pas',
  ZXing.BinaryBitmap in '..\ZXing.Delphi-3.10.0\Lib\Classes\Filtering\ZXing.BinaryBitmap.pas',
  ZXing.BitSource in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.BitSource.pas',
  ZXIng.ByteSegments in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXIng.ByteSegments.pas',
  ZXing.CharacterSetECI in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.CharacterSetECI.pas',
  ZXing.Common.BitArray in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.Common.BitArray.pas',
  ZXing.Common.BitArrayImplementation in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.Common.BitArrayImplementation.pas',
  ZXing.Common.BitMatrix in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.Common.BitMatrix.pas',
  ZXing.Common.Detector.MathUtils in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\Detector\ZXing.Common.Detector.MathUtils.pas',
  ZXing.Common.Detector.WhiteRectangleDetector in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\Detector\ZXing.Common.Detector.WhiteRectangleDetector.pas',
  ZXing.Common.DetectorResult in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.Common.DetectorResult.pas',
  ZXing.Common.GridSampler in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.Common.GridSampler.pas',
  ZXing.Common.PerspectiveTransform in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.Common.PerspectiveTransform.pas',
  ZXing.Common.ReedSolomon.GenericGF in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ReedSolomon\ZXing.Common.ReedSolomon.GenericGF.pas',
  ZXing.Common.ReedSolomon.ReedSolomonDecoder in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ReedSolomon\ZXing.Common.ReedSolomon.ReedSolomonDecoder.pas',
  ZXing.Datamatrix.DataMatrixReader in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\ZXing.Datamatrix.DataMatrixReader.pas',
  ZXing.Datamatrix.Internal.BitMatrixParser in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.BitMatrixParser.pas',
  ZXing.Datamatrix.Internal.DataBlock in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.DataBlock.pas',
  ZXing.Datamatrix.Internal.DecodedBitStreamParser in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.DecodedBitStreamParser.pas',
  ZXing.Datamatrix.Internal.Decoder in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.Decoder.pas',
  ZXing.Datamatrix.Internal.Detector in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Detector\ZXing.Datamatrix.Internal.Detector.pas',
  ZXing.Datamatrix.Internal.Version in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.Version.pas',
  ZXing.DecodeHintType in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.DecodeHintType.pas',
  ZXing.DecoderResult in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.DecoderResult.pas',
  ZXing.DefaultGridSampler in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.DefaultGridSampler.pas',
  ZXing.EncodeHintType in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.EncodeHintType.pas',
  ZXing.GlobalHistogramBinarizer in '..\ZXing.Delphi-3.10.0\Lib\Classes\Filtering\ZXing.GlobalHistogramBinarizer.pas',
  ZXing.Helpers in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.Helpers.pas',
  ZXing.HybridBinarizer in '..\ZXing.Delphi-3.10.0\Lib\Classes\Filtering\ZXing.HybridBinarizer.pas',
  ZXing.InvertedLuminanceSource in '..\ZXing.Delphi-3.10.0\Lib\Classes\Filtering\ZXing.InvertedLuminanceSource.pas',
  ZXing.LuminanceSource in '..\ZXing.Delphi-3.10.0\Lib\Classes\Filtering\ZXing.LuminanceSource.pas',
  ZXing.MultiFormatReader in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.MultiFormatReader.pas',
  ZXing.OneD.Code39Reader in '..\ZXing.Delphi-3.10.0\Lib\Classes\1D Barcodes\ZXing.OneD.Code39Reader.pas',
  ZXing.OneD.Code93Reader in '..\ZXing.Delphi-3.10.0\Lib\Classes\1D Barcodes\ZXing.OneD.Code93Reader.pas',
  ZXing.OneD.Code128Reader in '..\ZXing.Delphi-3.10.0\Lib\Classes\1D Barcodes\ZXing.OneD.Code128Reader.pas',
  ZXing.OneD.EAN8Reader in '..\ZXing.Delphi-3.10.0\Lib\Classes\1D Barcodes\ZXing.OneD.EAN8Reader.pas',
  ZXing.OneD.EAN13Reader in '..\ZXing.Delphi-3.10.0\Lib\Classes\1D Barcodes\ZXing.OneD.EAN13Reader.pas',
  ZXing.OneD.EANManufacturerOrgSupport in '..\ZXing.Delphi-3.10.0\Lib\Classes\1D Barcodes\ZXing.OneD.EANManufacturerOrgSupport.pas',
  ZXing.OneD.ITFReader in '..\ZXing.Delphi-3.10.0\Lib\Classes\1D Barcodes\ZXing.OneD.ITFReader.pas',
  ZXing.OneD.OneDReader in '..\ZXing.Delphi-3.10.0\Lib\Classes\1D Barcodes\ZXing.OneD.OneDReader.pas',
  ZXing.OneD.UPCAReader in '..\ZXing.Delphi-3.10.0\Lib\Classes\1D Barcodes\ZXing.OneD.UPCAReader.pas',
  ZXing.OneD.UPCEANExtension2Support in '..\ZXing.Delphi-3.10.0\Lib\Classes\1D Barcodes\ZXing.OneD.UPCEANExtension2Support.pas',
  ZXing.OneD.UPCEANExtension5Support in '..\ZXing.Delphi-3.10.0\Lib\Classes\1D Barcodes\ZXing.OneD.UPCEANExtension5Support.pas',
  ZXing.OneD.UPCEANExtensionSupport in '..\ZXing.Delphi-3.10.0\Lib\Classes\1D Barcodes\ZXing.OneD.UPCEANExtensionSupport.pas',
  ZXing.OneD.UPCEANReader in '..\ZXing.Delphi-3.10.0\Lib\Classes\1D Barcodes\ZXing.OneD.UPCEANReader.pas',
  ZXing.OneD.UPCEReader in '..\ZXing.Delphi-3.10.0\Lib\Classes\1D Barcodes\ZXing.OneD.UPCEReader.pas',
  ZXing.PlanarYUVLuminanceSource in '..\ZXing.Delphi-3.10.0\Lib\Classes\Filtering\ZXing.PlanarYUVLuminanceSource.pas',
  ZXing.QrCode.Internal.AlignmentPattern in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.AlignmentPattern.pas',
  ZXing.QrCode.Internal.AlignmentPatternFinder in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.AlignmentPatternFinder.pas',
  ZXing.QrCode.Internal.AlignmentPatternImplementation in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.AlignmentPatternImplementation.pas',
  ZXing.QrCode.Internal.BitMatrixParser in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.BitMatrixParser.pas',
  ZXing.QrCode.Internal.DataBlock in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.DataBlock.pas',
  ZXing.QrCode.Internal.DataMask in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.DataMask.pas',
  ZXing.QrCode.Internal.DecodedBitStreamParser in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.DecodedBitStreamParser.pas',
  ZXing.QrCode.Internal.Decoder in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.Decoder.pas',
  ZXing.QrCode.Internal.Detector in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.Detector.pas',
  ZXing.QrCode.Internal.ErrorCorrectionLevel in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.ErrorCorrectionLevel.pas',
  ZXing.QrCode.Internal.FinderPattern in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPattern.pas',
  ZXing.QrCode.Internal.FinderPatternFinder in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPatternFinder.pas',
  ZXing.QrCode.Internal.FinderPatternImplementation in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPatternImplementation.pas',
  ZXing.QrCode.Internal.FinderPatternInfo in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPatternInfo.pas',
  ZXing.QrCode.Internal.FormatInformation in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.FormatInformation.pas',
  ZXing.QrCode.Internal.Mode in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.Mode.pas',
  ZXing.QrCode.Internal.QRCodeDecoderMetaData in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.QRCodeDecoderMetaData.pas',
  ZXing.QrCode.Internal.Version in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.Version.pas',
  ZXing.QrCode.QRCodeReader in '..\ZXing.Delphi-3.10.0\Lib\Classes\2D Barcodes\ZXing.QrCode.QRCodeReader.pas',
  ZXing.Reader in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.Reader.pas',
  ZXing.ReadResult in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.ReadResult.pas',
  ZXing.ResultMetadataType in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.ResultMetadataType.pas',
  ZXing.ResultPoint in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.ResultPoint.pas',
  ZXing.ResultPointImplementation in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.ResultPointImplementation.pas',
  ZXing.RGBLuminanceSource in '..\ZXing.Delphi-3.10.0\Lib\Classes\Filtering\ZXing.RGBLuminanceSource.pas',
  ZXing.ScanManager in '..\ZXing.Delphi-3.10.0\Lib\Classes\ZXing.ScanManager.pas',
  ZXing.StringUtils in '..\ZXing.Delphi-3.10.0\Lib\Classes\Common\ZXing.StringUtils.pas',
  DelphiZXIngQRCode in '..\ZXing.Delphi-3.10.0\DelphiZXingQRCode-master\Source\DelphiZXIngQRCode.pas',
  uFrameIssuies in 'uFrameIssuies.pas' {FrameIssuies: TFrame},
  controls.item in 'controls.item.pas',
  controls.listitem in 'controls.listitem.pas',
  uFrameBag in 'uFrameBag.pas',
  uFrameBagSection in 'uFrameBagSection.pas' {FrameBagSection: TFrame};

{$R *.res}

begin
  Application.Initialize;
  Application.FormFactor.Orientations := [TFormOrientation.Landscape, TFormOrientation.InvertedLandscape];
  Application.CreateForm(TMainForm, MainForm);
  Application.Run;
end.
